### ISSUE TITLE
Parent/Child Models not populating

### ISSUE THREAD

**Issue by stevekaeser** [innoverio/vscode-dbt-power-user#104]
I'm not seeing anything populating under Parent/Child Models. Here is the error that I'm seeing in the console:

`[Extension Host] stack trace: Error: Illegal argument: pattern	at y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1247)	at new qt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:47358)	at new qt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:17955)	at h.createTargetFolderWatcher (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:279286)	at h.<anonymous> (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:278717)	at Generator.next (<anonymous>)	at /Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:293629	at new Promise (<anonymous>)	at Module.h (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:293374)	at h.onProjectConfigChanged (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:278177)	at /Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:277979	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)	at h.<anonymous> (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:268722)	at Generator.next (<anonymous>)	at /Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:293629	at new Promise (<anonymous>)	at Module.h (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:293374)	at h.refresh (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:268400)	at h.<anonymous> (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:266956)	at Generator.next (<anonymous>)	at /Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:293629	at new Promise (<anonymous>)	at Module.h (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:293374)	at h.tryRefresh (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:266899)	at u.<anonymous> (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:273583)	at Generator.next (<anonymous>)	at o (/Users/username/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.12/dist/extension.js:2:293431)	at processTicksAndRejections (internal/process/task_queues.js:93:5)
I @ workbench.desktop.main.js:sourcemap:75`

**Comment by alexrosenfeld10** [comment]
yeah, I see this too. It's empty. otherwise the extension works though, for jumping to references and things

**Comment by alexrosenfeld10** [comment]
I don't the logs though

**Comment by shr1k** [comment]
I have the same issue, and in addition I can't jump to definitions and references either. The extension loading debug output shows me this error:

```
[2022-02-23 08:58:48.160] [exthost] [error] Activating extension innoverio.vscode-dbt-power-user failed due to an error:
[2022-02-23 08:58:48.160] [exthost] [error] Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at _ (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:64832)
	at Object.get testResults [as testResults] (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:33817)
	at w.activate (/home/shrikant/.vscode-insiders/extensions/ms-python.python-2022.1.1869134244-dev/out/client/extension.js:85:74911)
	at /home/shrikant/.vscode-insiders/extensions/ms-python.python-2022.1.1869134244-dev/out/client/extension.js:67:87919
	at Array.map (<anonymous>)
	at f.activateWorkspace (/home/shrikant/.vscode-insiders/extensions/ms-python.python-2022.1.1869134244-dev/out/client/extension.js:67:87910)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I'm not aware of any changes to the Python plugin recently though??

**Comment by shr1k** [comment]
FWIW, everything with the extension works fine when I start VS Code with the `--enable-proposed-api ms-python.python` switch mentioned in the error message.

**Comment by mdesmet** [comment]
It seems a different issue then the original issue. You seem to be using insiderds vscode. May be that there is a mspython update coming that breaks some feature we rely upon.

**Comment by shr1k** [comment]
Noted, thanks @mdesmet -- I'll keep an eye out for any change in behaviour and also check the insider build changelogs!

**Comment by Startouf** [comment]
This bug was reported there https://github.com/microsoft/vscode/issues/143834

**Comment by Kiollpt** [comment]
I am seeing the similar problem 
---
Version: 1.65.1 (Universal)
Commit: 8908a9
OS: Darwin x64
```
[[object Object]]Illegal argument: pattern
Error: Illegal argument: pattern
	at D (vscode-file://vscode-app/private/var/folders/2z/hk6ph1914y93rdwp1vn67p980000gn/T/AppTranslocation/148FC8CE-60AA-4733-97FF-E7AADAEC813E/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:5)
	at new Ct (vscode-file://vscode-app/private/var/folders/2z/hk6ph1914y93rdwp1vn67p980000gn/T/AppTranslocation/148FC8CE-60AA-4733-97FF-E7AADAEC813E/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76)
	at new Ct (vscode-file://vscode-app/private/var/folders/2z/hk6ph1914y93rdwp1vn67p980000gn/T/AppTranslocation/148FC8CE-60AA-4733-97FF-E7AADAEC813E/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76)
	at u.createTargetFolderWatcher (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at u.<anonymous> (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at Generator.next (<anonymous>)
	at vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2
	at new Promise (<anonymous>)
	at Module.u (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at u.onProjectConfigChanged (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2
	at d.invoke (vscode-file://vscode-app/private/var/folders/2z/hk6ph1914y93rdwp1vn67p980000gn/T/AppTranslocation/148FC8CE-60AA-4733-97FF-E7AADAEC813E/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58)
	at w.fire (vscode-file://vscode-app/private/var/folders/2z/hk6ph1914y93rdwp1vn67p980000gn/T/AppTranslocation/148FC8CE-60AA-4733-97FF-E7AADAEC813E/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58)
	at u.<anonymous> (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at Generator.next (<anonymous>)
	at vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2
	at new Promise (<anonymous>)
	at Module.u (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at u.refresh (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at u.<anonymous> (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at Generator.next (<anonymous>)
	at vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2
	at new Promise (<anonymous>)
	at Module.u (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at u.tryRefresh (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at c.<anonymous> (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at Generator.next (<anonymous>)
	at s (vscode-file://vscode-app/Users/harry/.vscode/extensions/innoverio.vscode-dbt-power-user-0.5.13/dist/extension.js:2)
	at processTicksAndRejections (internal/process/task_queues.js:93)
```

**Comment by mdesmet** [comment]
Can you guys retest? I think this issue might be the same as #57 ? Should be fixed with latest version.

**Comment by stevekaeser** [comment]
This appears to be fixed for me now. Thanks.
