### ISSUE TITLE
'dbtPowerUser.showCompiledSQL' not found

### ISSUE THREAD

**Issue by puruzio** [innoverio/vscode-dbt-power-user#122]
the issue is that the extension can't be activated, could you check the console log through Help >> Toggle Developer tools and post the log. It might be that the extension can't read your dbt_project.yml file (invalid yaml).

_Originally posted by @mdesmet in https://github.com/innoverio/vscode-dbt-power-user/issues/100#issuecomment-1026279968_

**Comment by puruzio** [comment]
Reopening this issue with the browser console log that I previously did not include in the issue as I thought nothing in it was relevant. It may be the case, but I wanted to at least have someone look at it in case I'm missing something.

```

ARN Skipping extension /c:/Users/p805649/.vscode/extensions/ms-vscode.references-view-0.0.89 with lower version 0.0.89.
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///c%3A/Users/p805649/.vscode/extensions/ms-mssql.mssql-1.16.0/syntaxes/SQL.plist
register @ TMScopeRegistry.ts:47
console.ts:137 [Extension Host] ElixirLS: starting client for file:///y%3A/elixir-stuff/livebook with server options Object client options Object
log.ts:301  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
console.ts:137 [Extension Host] logFile for SqlToolsResourceProviderService.exe is c:\Users\p805649\AppData\Roaming\Code\logs\20220827T214146\exthost1\ms-mssql.mssql\resourceprovider.log
console.ts:137 [Extension Host] This process (ui Extenstion Host) is pid: 8472
console.ts:137 [Extension Host] Old log files deletion report: {}
localProcessExtensionHost.ts:309 Extension Host
localProcessExtensionHost.ts:310 Debugger attached.
log.ts:301  INFO UNRESPONSIVE extension host: starting to profile NOW
console.ts:137 [Extension Host]% {message: 'Git error', stdout: '', stderr: "fatal: y:\\elixir-stuff\\livebook\\config\\config.exs:…ivebook\\config\\config.exs' is outside repository\n", exitCode: 128}
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:473
_invokeHandler @ rpcProtocol.ts:458
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
L @ ipc.net.ts:60
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Git error {  "exitCode": 128,  "stdout": "",  "stderr": "fatal: y:\\elixir-stuff\\livebook\\config\\config.exs: 'y:\\elixir-stuff\\livebook\\config\\config.exs' is outside repository\n"}
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:473
_invokeHandler @ rpcProtocol.ts:458
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
L @ ipc.net.ts:60
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
log.ts:313   ERR Git error
73console.ts:137 [Extension Host] rejected promise not handled within 1 second: Git error {  "exitCode": 128,  "stdout": "",  "stderr": "fatal: y:\\elixir-stuff\\livebook\\config\\config.exs: 'y:\\elixir-stuff\\livebook\\config\\config.exs' is outside repository\n"}

```

**Comment by puruzio** [comment]
![image](https://user-images.githubusercontent.com/1150766/187058479-43c8d470-cf83-4683-879b-cc4b924a99cf.png)

**Comment by puruzio** [comment]
`console.ts:137 [Extension Host] File not found at 'C:\Users\i805649\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\include\sqlserver\macros\adapters\columns.sql', probably compiled is outdated! Error: ENOENT: no such file or directory, open 'C:\Users\i805649\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\include\sqlserver\macros\adapters\columns.sql'
	at Object.openSync (node:fs:585:3)
	at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
	at Object.readFileSync (node:fs:453:35)
	at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:107513
	at Array.forEach (<anonymous>)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:107387
	at new Promise (<anonymous>)
	at r.createMacroMetaMap (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:107277)
	at r.<anonymous> (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:106367)
	at Generator.next (<anonymous>)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118759
	at new Promise (<anonymous>)
	at Module.u (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118504)
	at r.parseManifest (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:105995)
	at u.<anonymous> (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:103735)
	at Generator.next (<anonymous>)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118759
	at new Promise (<anonymous>)
	at Module.u (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118504)
	at u.onProjectConfigChanged (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:102963)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:102765
	at g.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at u.<anonymous> (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:93708)
	at Generator.next (<anonymous>)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118759
	at new Promise (<anonymous>)
	at Module.u (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118504)
	at u.refresh (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:93384)
	at u.<anonymous> (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:91787)
	at Generator.next (<anonymous>)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118759
	at new Promise (<anonymous>)
	at Module.u (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118504)
	at u.tryRefresh (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:91730)
	at c.<anonymous> (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:98369)
	at Generator.next (<anonymous>)
	at s (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118561)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
console.ts:137 [Extension Host] File not found at 'C:\Users\i805649\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\include\sqlserver\macros\adapters\freshness.sql', probably compiled is outdated! Error: ENOENT: no such file or directory, open 'C:\Users\i805649\AppData\Local\Programs\Python\Python39\lib\site-packages\dbt\include\sqlserver\macros\adapters\freshness.sql'
	at Object.openSync (node:fs:585:3)
	at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
	at Object.readFileSync (node:fs:453:35)
	at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:107513
	at Array.forEach (<anonymous>)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:107387
	at new Promise (<anonymous>)
	at r.createMacroMetaMap (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:107277)
	at r.<anonymous> (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:106367)
	at Generator.next (<anonymous>)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118759
	at new Promise (<anonymous>)
	at Module.u (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118504)
	at r.parseManifest (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:105995)
	at u.<anonymous> (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:103735)
	at Generator.next (<anonymous>)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118759
	at new Promise (<anonymous>)
	at Module.u (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118504)
	at u.onProjectConfigChanged (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:102963)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:102765
	at g.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at b.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:2265)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1843)
	at u.<anonymous> (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:93708)
	at Generator.next (<anonymous>)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118759
	at new Promise (<anonymous>)
	at Module.u (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118504)
	at u.refresh (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:93384)
	at u.<anonymous> (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:91787)
	at Generator.next (<anonymous>)
	at c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118759
	at new Promise (<anonymous>)
	at Module.u (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118504)
	at u.tryRefresh (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:91730)
	at c.<anonymous> (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:98369)
	at Generator.next (<anonymous>)
	at s (c:\Users\p805649\.vscode\extensions\innoverio.vscode-dbt-power-user-0.6.2\dist\extension.js:2:118561)
	at processTicksAndRejections (node:internal/process/task_queues:96:`
