### ISSUE TITLE
dbt-oracle : Runtime error not connected when executing a model 

### ISSUE THREAD

**Issue by Mirko-T** [innoverio/vscode-dbt-power-user#201]
### Expected behavior

When running a query from .sql model expected to see result set 

### Actual behavior

- dbt debug works fine
- dbt run works fine
- VSCode DBT PowerUser extension fails to execute. Error message is: `Runtime Error not connected`

### Steps To Reproduce

Executing a model produces this error.

### Log output/Screenshots

```



{
  "code": -1,
  "message": "Runtime Error\n  Runtime Error\n    not connected",
  "data": "\"Error: Traceback (most recent call last):\\n  File \\\"\\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\oracle\\\\connections.py\\\", line 223, in exception_handler\\n    yield\\n  File \\\"\\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\oracle\\\\connections.py\\\", line 275, in add_query\\n    cursor = connection.handle.cursor()\\ncx_Oracle.InterfaceError: not connected\\n\\nThe above exception was the direct cause of the following exception:\\n\\nTraceback (most recent call last):\\n  File \\\".vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.9.0\\\\dist\\\\dbt_integration.py\\\", line 413, in execute_sql\\n    *self.adapter_execute(compiled_sql, fetch=True),\\n  File \\\".vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.9.0\\\\dist\\\\dbt_integration.py\\\", line 392, in adapter_execute\\n    return self.adapter.execute(sql, auto_begin, fetch)\\n  File \\\"\\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\base\\\\impl.py\\\", line 225, in execute\\n    return self.connections.execute(\\n  File \\\"\\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\sql\\\\connections.py\\\", line 127, in execute\\n    _, cursor = self.add_query(sql, auto_begin)\\n  File \\\"\\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\oracle\\\\connections.py\\\", line 279, in add_query\\n    return connection, cursor\\n  File \\\"\\\lib\\\\contextlib.py\\\", line 135, in __exit__\\n    self.gen.throw(type, value, traceback)\\n  File \\\"\\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\oracle\\\\connections.py\\\", line 246, in exception_handler\\n    raise dbt.exceptions.RuntimeException(e) from e\\ndbt.exceptions.RuntimeException: Runtime Error\\n  not connected\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\".vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.9.0\\\\dist\\\\node_python_bridge.py\\\", line 104, in <module>\\n    value = eval(_compile(data['code'], '<input>', 'eval'), _locals)\\n  File \\\"<input>\\\", line 1, in <module>\\n  File \\\".vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.9.0\\\\dist\\\\dbt_integration.py\\\", line 418, in execute_sql\\n    raise RuntimeException(str(e))\\ndbt.exceptions.RuntimeException: Runtime Error\\n  Runtime Error\\n    not connected\\n\\n\\tat ChildProcess.onMessage (.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.9.0\\\\dist\\\\extension.js:4796:184)\\n\\tat Object.onceWrapper (node:events:646:26)\\n\\tat ChildProcess.emit (node:events:526:28)\\n\\tat emit (node:internal/child_process:938:14)\\n\\tat process.processTicksAndRejections (node:internal/process/task_queues:84:21)\""
}



```

### Operating System

windows 10 

### dbt version

1.3.0, 1.0.6

### dbt Adapter

dbt-oracle 

### dbt Power User version

0.9.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
That's interesting.  Anything particular on how you connect? do you use environment variables in your `profiles.yml`?

**Comment by Mirko-T** [comment]
Yes, I use environment variables for pass.

**Comment by geoHeil** [comment]
Hi,
I can observe the same problem. For me, even with a hardcoded value in profiles.yaml for the password this error persists.

**Comment by Mirko-T** [comment]
They are set for my user account, but for me also hard coding values in profiles.yaml doesn't work.

**Comment by mdesmet** [comment]
@geoHeil : also on Oracle?

**Comment by geoHeil** [comment]
yes

**Comment by mdesmet** [comment]
AFAIK this issue is limited to the Oracle connector. If I would give you a python script, would any of you be able to debug it and find what is breaking?

**Comment by mdesmet** [comment]
download the file from: https://github.com/innoverio/vscode-dbt-power-user/blob/master/dbt_integration.py

```
from dbt_integration import *
project = DbtProject(profiles_dir='absolute path to profile directory', project_dir='absolute path to project directory')
print(project.execute_sql('select 1'))
```

Try to determine why the connection is not open.

**Comment by geoHeil** [comment]
```
 print(project.execute_sql('select 1'))
12:52:13  oracle adapter: Rolling back transaction.
Traceback (most recent call last):
  File "\lib\site-packages\dbt\adapters\oracle\connections.py", line 223, in exception_handler
    yield
  File "\lib\site-packages\dbt\adapters\oracle\connections.py", line 275, in add_query
    cursor = connection.handle.cursor()
cx_Oracle.InterfaceError: not connected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "\debugging.py", line 413, in execute_sql
    *self.adapter_execute(compiled_sql, fetch=True),
  File "\debugging.py", line 392, in adapter_execute
    return self.adapter.execute(sql, auto_begin, fetch)
  File "\lib\site-packages\dbt\adapters\base\impl.py", line 225, in execute
    return self.connections.execute(
  File "\lib\site-packages\dbt\adapters\sql\connections.py", line 127, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "\lib\site-packages\dbt\adapters\oracle\connections.py", line 279, in add_query
    return connection, cursor
  File "\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "\lib\site-packages\dbt\adapters\oracle\connections.py", line 246, in exception_handler
    raise dbt.exceptions.RuntimeException(e) from e
dbt.exceptions.RuntimeException: Runtime Error
  not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\debugging.py", line 418, in execute_sql
    raise RuntimeException(str(e))
dbt.exceptions.RuntimeException: Runtime Error
  Runtime Error
    not connected
```

However, it gets a bit more tricky. The above error is the result of executing the `SELECT 1` twice.

When executing it for a first time, the error looks like:


```
>>> print(project.execute_sql('select 1'))
12:53:58  oracle adapter: Oracle error: ORA-00923: FROM keyword not found where expected
Traceback (most recent call last):
  File "\lib\site-packages\dbt\adapters\oracle\connections.py", line 223, in exception_handler
    yield
  File "\lib\site-packages\dbt\adapters\oracle\connections.py", line 276, in add_query
    cursor.execute(sql, bindings)
cx_Oracle.DatabaseError: ORA-00923: FROM keyword not found where expected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "\debugging.py", line 413, in execute_sql
    *self.adapter_execute(compiled_sql, fetch=True),
  File "\debugging.py", line 392, in adapter_execute
    return self.adapter.execute(sql, auto_begin, fetch)
  File "\lib\site-packages\dbt\adapters\base\impl.py", line 225, in execute
    return self.connections.execute(
  File "\lib\site-packages\dbt\adapters\sql\connections.py", line 127, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "\lib\site-packages\dbt\adapters\oracle\connections.py", line 279, in add_query
    return connection, cursor
  File "\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "\lib\site-packages\dbt\adapters\oracle\connections.py", line 235, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error
  ORA-00923: FROM keyword not found where expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\debugging.py", line 418, in execute_sql
    raise RuntimeException(str(e))
dbt.exceptions.RuntimeException: Runtime Error
  Database Error
    ORA-00923: FROM keyword not found where expected
```

**Comment by mdesmet** [comment]
So basically when the transaction fails the connection is closed?

As long as the transaction doesn't fail the connection stays open?

Can you confirm this with multiple exeucutions with the correct syntax `select 1 from dual`.

**Comment by geoHeil** [comment]
Indeed:
```
 print(project.execute_sql('select 1 from dual'))
<debugging.DbtAdapterExecutionResult object at 0x000002004699E850>

```

this looks like it is working

**Comment by mdesmet** [comment]
Ok thanks, that insight may be something i can work with.

**Comment by mdesmet** [comment]
Can you try following?

```
from dbt_integration import *
project = DbtProject(profiles_dir='absolute path to profile directory', project_dir='absolute path to project directory')
# should fail
try:
    print(project.execute_sql('select 1'))
except Exception as e:
    print(str(e))
# should clean up ?
project.adapter.cleanup_all()

# should work
print(project.execute_sql('select 1 from dual'))
```

**Comment by geoHeil** [comment]
No:

```
project.adapter.cleanup_all()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'OracleAdapter' object has no attribute 'cleanup_all'
```

**Comment by mdesmet** [comment]
Fixed in 0.9.5. Thanks @geoHeil for helping debug this!

**Comment by geoHeil** [comment]
I still get the same exceptions on 0.9.5 though

**Comment by Mirko-T** [comment]
Hi, the error has changed for me with the version 0.9.5. I'm now constantly getting:

Runtime Error
Database Error ORA-00933: SQL command not properly ended

Error details:

```

{
  "code": -1,
  "message": "Runtime Error\n  Database Error\n    ORA-00933: SQL command not properly ended",
  "data": "\"Error: Traceback (most recent call last):\\n  File \\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\oracle\\\\connections.py\\\", line 222, in exception_handler\\n    yield\\n  File \\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\oracle\\\\connections.py\\\", line 275, in add_query\\n    cursor.execute(sql, bindings)\\ncx_Oracle.DatabaseError: ORA-00933: SQL command not properly ended\\n\\nThe above exception was the direct cause of the following exception:\\n\\nTraceback (most recent call last):\\n  File \\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.9.5\\\\dist\\\\dbt_integration.py\\\", line 413, in execute_sql\\n    *self.adapter_execute(compiled_sql, fetch=True),\\n  File \\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.9.5\\\\dist\\\\dbt_integration.py\\\", line 391, in adapter_execute\\n    return self.adapter.execute(sql, auto_begin, fetch)\\n  File \\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\base\\\\impl.py\\\", line 278, in execute\\n    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch)\\n  File \\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\sql\\\\connections.py\\\", line 123, in execute\\n    _, cursor = self.add_query(sql, auto_begin)\\n  File \\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\oracle\\\\connections.py\\\", line 278, in add_query\\n    return connection, cursor\\n  File \\\lib\\\\contextlib.py\\\", line 135, in __exit__\\n    self.gen.throw(type, value, traceback)\\n  File \\\lib\\\\site-packages\\\\dbt\\\\adapters\\\\oracle\\\\connections.py\\\", line 234, in exception_handler\\n    raise dbt.exceptions.DatabaseException(str(e).strip()) from e\\ndbt.exceptions.DatabaseException: Database Error\\n  ORA-00933: SQL command not properly ended\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.9.5\\\\dist\\\\node_python_bridge.py\\\", line 104, in <module>\\n    value = eval(_compile(data['code'], '<input>', 'eval'), _locals)\\n  File \\\"<input>\\\", line 1, in <module>\\n  File \\\.vscode\\\\extensions\\\\innoverio.vscode-dbt-power-user-0.9.5\\\\dist\\\\dbt_integration.py\\\", line 418, in execute_sql\\n    raise RuntimeException(str(e))\\ndbt.exceptions.RuntimeException: Runtime Error\\n  Database Error\\n    ORA-00933: SQL command not properly ended\\n\\n\\tat ChildProcess.onMessage (\\\extensions\\\\innoverio.vscode-dbt-power-user-0.9.5\\\\dist\\\\extension.js:4796:184)\\n\\tat Object.onceWrapper (node:events:646:26)\\n\\tat ChildProcess.emit (node:events:526:28)\\n\\tat emit (node:internal/child_process:938:14)\\n\\tat process.processTicksAndRejections (node:internal/process/task_queues:84:21)\""
}

```

**Comment by mdesmet** [comment]
This seems unrelated. Can you also check which query is being executed and post it here?

**Comment by mdesmet** [comment]
Note to self: add all this information to the exception.

**Comment by Mirko-T** [comment]
I'm getting this error while executing any dbt SQL. 

For example this one: 

select 1 from dual

As a side note, other commands are working as expected (run dbt model, run dbt tests, compiled dbt preview).

**Comment by mdesmet** [comment]
OK I think i know what is your issue:

Please override `dbt.queryTemplate` in vscode settings with the following setting:

`select * from (select * from ({query})) where ROWNUM <= {limit}` instead of the default `select * from ({query}) as query limit {limit}`.

**Comment by Mirko-T** [comment]
That's it, big thanks! Query results now preview as expected.

**Comment by geoHeil** [comment]
@mdesmet great! Would it be possible to document this somewhere or perhaps change this default behavior?

**Comment by mdesmet** [comment]
Check the README. It is documented already.
