### ISSUE TITLE
Issues when using Github codespaces

### ISSUE THREAD

**Issue by nicor88** [innoverio/vscode-dbt-power-user#563]
### Expected behavior

I'm trying to configure vscode-dbt-power-user in Github codespaces, but somehow I'm getting different issues:
* `An unexpected error occured while initializing the dbt project: Error: Python process closed with exit code 0.If the issue persists, please seek help in our dbt`
* `An error occured while trying to generate the model name 'project' is not defined` when I try to generate models from sources
* ```Encountered an unknown issue:Error: Traceback (most recent call last): File "/home/vscode/.vscode-remote/extensions/innoverio.vscode-dbt-power-user-0.17.4/dist/node_python_bridge.py", line 104, in <module> value = eval(_compile(data['code'], '<input>', 'eval'), _locals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<input>", line 1, in <module> NameError: name 'project' is not defined .If the issue persists, please seek help in our dbt```

### Actual behavior

Getting few errors with the plugin

### Steps To Reproduce

Create a new codespace with the follwing customizations:

```
"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			"settings": {
				"workbench.colorTheme": "Default Dark Modern" 
			},
			"extensions": [
				"github.vscode-pull-request-github",
				"GitHub.copilot",
				"GitHub.copilot-chat",
				"innoverio.vscode-dbt-power-user"
			]
		}
	},
```

Also I use mcr.microsoft.com/devcontainers/python:0-3.11-bullseye as Docker image, and install plain dbt in there

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)" NAME="Debian GNU/Linux" VERSION_ID="11" VERSION="11 (bullseye)" VERSION_CODENAME=bullseye ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

### dbt version

1.6.0

### dbt Adapter

dbt-athena-community==1.6.0

### dbt Power User version

latest

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by nicor88** [comment]
This has being fixed using this https://github.com/dbt-labs/jaffle_shop_duckdb/blob/duckdb as reference.
